default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>
  timeout: 5000
  adapter: <%= ENV.fetch('DB_ADAPTER') { 'postgresql' } %>
  username: <%= ENV.fetch('DB_USERNAME') { 'chikito' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { 'chikito' } %>
  encoding: utf-8

development:
  <<: *default
  database: <%= ENV.fetch('DB_NAME') { 'chikito_dev' } %>

test:
  <<: *default
  database: <%= ENV.fetch('DB_NAME') { 'chikito_test' } %>

staging:
  <<: *default
  database: <%= ENV.fetch('DB_NAME') { 'chikito_staging' } %>

production:
  <<: *default
  database: <%= ENV.fetch('DB_NAME') { 'chikito_production' } %>
